apiVersion: v1
kind: Service
metadata:
  name: mysql-service
  labels:
    app: mysql
spec:
  type: ClusterIP
  ports:
    - name: mysql
      port: 6025
      targetPort: 3306
  selector:
    app: mysql
