apiVersion: v1
kind: Pod
metadata:
  name: httpie-get
spec:
  containers:
  - name: get
    image: clue/httpie
    args: ["GET", "develop-httpbin-service/get", "--check-status"]
  restartPolicy: Never
