apiVersion: skaffold/v2alpha1
kind: Config

profiles:
  - name: develop
    build:
      tagPolicy:
        envTemplate:
          template: "{{.IMAGE_NAME}}:{{.GIT_BRANCH}}"
      artifacts:
      - image: your-registry/test
    deploy:
      kustomize:
        path: "./deployment/overlay/develop"
