apiVersion: v1
kind: Service
metadata:
  name: httpbin-service
  labels:
    app: httpbin
spec:
  type: ClusterIP
  ports:
    - name: httpbin
      port: 80
      targetPort: 80
  selector:
    app: httpbin
